Repository AY2425S2-CS2103T-T12-3/tp, pull requests merged in 2025-04, with the labels that each got.

#165 Add test cases and bugfixes
  src/main/java/seedu/address/logic/commands/event/FindEventCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/client/AddClientCommandParser.java
  src/main/java/seedu/address/logic/parser/client/DeleteClientCommandParser.java
  src/main/java/seedu/address/logic/parser/client/EditClientCommandParser.java
  src/main/java/seedu/address/logic/parser/client/FindClientCommandParser.java
  src/main/java/seedu/address/logic/parser/deal/AddDealCommandParser.java
  src/main/java/seedu/address/logic/parser/deal/FindDealCommandParser.java
  src/main/java/seedu/address/logic/parser/deal/UpdateDealCommandParser.java
  src/main/java/seedu/address/logic/parser/event/EditEventCommandParser.java
  src/main/java/seedu/address/logic/parser/event/FindEventCommandParser.java
  src/main/java/seedu/address/logic/parser/property/AddPropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/property/DeletePropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/property/EditPropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/property/FindPropertyCommandParser.java
  src/test/java/seedu/address/logic/commands/event/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/FindEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/ListEventCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/client/FindClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/deal/FindDealCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/FindEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/property/DeletePropertyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/property/FindPropertyCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: priority.Medium

#185 Fix bug when editing event date field
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/event/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/event/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/event/EditEventCommandParser.java
  src/test/java/seedu/address/logic/commands/event/AddEventCommandTest.java
Labels: severity.Medium, alpha-bug

#257 Branch bug fixing
  docs/UserGuide.md
  docs/diagrams/CommandStructure.puml
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/logic/parser/property/AddPropertyCommandParser.java
  src/main/java/seedu/address/model/property/Property.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/client/EditClientCommandTest.java
  src/test/java/seedu/address/logic/commands/deal/AddDealCommandTest.java
  src/test/java/seedu/address/logic/commands/deal/UpdateDealCommandTest.java
  src/test/java/seedu/address/logic/parser/property/AddPropertyCommandParserTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/model/property/UniquePropertyListTest.java
  src/test/java/seedu/address/testutil/PropertyBuilder.java
  src/test/java/seedu/address/testutil/TypicalProperties.java
Labels: alpha-bug

#260 Fix bugs
  src/main/java/seedu/address/logic/commands/property/EditPropertyCommand.java
  src/main/java/seedu/address/model/client/Phone.java
  src/main/java/seedu/address/model/property/Property.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/deal/UpdateDealCommandTest.java
  src/test/java/seedu/address/logic/commands/property/EditPropertyCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/client/FindClientCommandParserTest.java
  src/test/java/seedu/address/model/client/predicates/ClientNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
Labels: type.Bug

#266 Fix: Block deletion of active properties
  src/main/java/seedu/address/logic/commands/property/DeletePropertyCommand.java
Labels: severity.Medium, alpha-bug

#264 Update: fix numerous bugs after PE-D
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
Labels: type.Bug

#271 Update UG
  docs/UserGuide.md
  src/main/java/seedu/address/model/client/ClientName.java
Labels: priority.Medium

#276 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
Labels: priority.Medium

#277 Update: fix numerous bugs related to price and update DG
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/property/EditPropertyCommandParser.java
  src/test/java/seedu/address/logic/parser/property/EditPropertyCommandParserTest.java
Labels: type.Bug

#281 Various bugfixes
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/client/FindClientCommand.java
  src/main/java/seedu/address/logic/commands/deal/FindDealCommand.java
  src/main/java/seedu/address/logic/commands/event/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/property/FindPropertyCommand.java
  src/main/java/seedu/address/model/event/Event.java
  src/test/java/seedu/address/logic/commands/client/FindClientCommandTest.java
  src/test/java/seedu/address/logic/commands/deal/FindDealCommandTest.java
  src/test/java/seedu/address/logic/commands/event/FindEventCommandTest.java
  src/test/java/seedu/address/logic/commands/property/FindPropertyCommandTest.java
  src/test/java/seedu/address/model/event/EventTest.java
Labels: severity.Medium, alpha-bug
