Repository AY2425S2-CS2103T-T12-3/tp, pull requests merged in 2025-03, with the labels that each got.

#54 Update Developer Guide
  docs/DeveloperGuide.md
Labels: priority.High

#113 Update: maintain events in chronological order
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
Labels: type.Enhancement

#121 Add JavaDoc
  src/main/java/seedu/address/logic/commands/event/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/event/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/event/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/event/ListEventCommand.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventType.java
Labels: type.Task, severity.VeryLow

#119 Add test cases
  TODO.txt
  src/main/java/seedu/address/logic/commands/event/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/event/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/event/AddEventCommandParser.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Note.java
  src/test/java/seedu/address/logic/commands/client/DeleteClientCommandTest.java
  src/test/java/seedu/address/logic/commands/client/EditClientCommandTest.java
  src/test/java/seedu/address/logic/commands/client/ListClientCommandTest.java
  src/test/java/seedu/address/logic/commands/event/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/ListEventCommandTest.java
  src/test/java/seedu/address/logic/commands/property/DeletePropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/property/EditPropertyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/client/DeleteClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/client/EditClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/deal/AddDealCommandParserTest.java
  src/test/java/seedu/address/logic/parser/deal/UpdateDealCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/DeleteEventCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalDeals.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task

#128 Enhance UI
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/client/AddClientCommand.java
  src/main/java/seedu/address/logic/parser/deal/AddDealCommandParser.java
  src/main/java/seedu/address/logic/parser/deal/FindDealCommandParser.java
  src/main/java/seedu/address/logic/parser/deal/UpdateDealCommandParser.java
  src/main/java/seedu/address/model/deal/DealStatus.java
  src/main/java/seedu/address/model/property/Description.java
  src/main/java/seedu/address/model/property/Size.java
  src/main/java/seedu/address/storage/JsonAdaptedProperty.java
  src/main/java/seedu/address/ui/cards/ClientCard.java
  src/main/java/seedu/address/ui/cards/DealCard.java
  src/main/java/seedu/address/ui/cards/EventCard.java
  src/main/java/seedu/address/ui/cards/PropertyCard.java
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PropertyListCard.fxml
  src/test/java/seedu/address/logic/parser/deal/AddDealCommandParserTest.java
  src/test/java/seedu/address/logic/parser/deal/UpdateDealCommandParserTest.java
  src/test/java/seedu/address/model/property/DescriptionTest.java
  src/test/java/seedu/address/model/property/SizeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPropertyTest.java
  src/test/java/seedu/address/testutil/PropertyUtil.java
  src/test/java/seedu/address/testutil/TypicalDeals.java
Labels: type.Enhancement

#130 Add logging to event commands
  src/main/java/seedu/address/logic/commands/deal/FindDealCommand.java
  src/main/java/seedu/address/logic/commands/event/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/event/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/event/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/event/ListEventCommand.java
  src/main/java/seedu/address/logic/parser/deal/FindDealCommandParser.java
  src/main/java/seedu/address/logic/parser/event/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/event/DeleteEventCommandParser.java
  src/main/java/seedu/address/logic/parser/event/FindEventCommandParser.java
Labels: type.Task
